### PR TITLE
Update for 1.17

### PR DESCRIPTION
**Pull request by rikusen0335**
I haven't tested all of them but I assume they should work.

### CODE REVIEW

**Comment by pattlebass** [comment]
There are some unnecessary tabs. I guess they don't matter but I think you should remove them. Also, you should update `pack_format` in `pack.mcmeta` to 7.

**Comment by rikusen0335** [comment]
Nice, gotta update it in a day

**Comment by helpimnotdrowning** [comment]
thanks for this, kinda forgot about this datapack

**Comment by rikusen0335** [comment]
Thanks for the fix, and thank you for making this pack

**Pull request merged**
